import type { Metadata } from "next"
import { Toaster } from "@/components/ui/toaster"
import { PayPalProvider } from "@/contexts/PayPalContext"
import { payPalConfig } from "@/services/paypal"
import { Inter } from "next/font/google"
// import ConfigureAmplifyClientSide from "./ConfigureAmplifyClientSide"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })
const { payPalClientId, payPalSDKUrl } = payPalConfig

export const metadata: Metadata = {
  title: "Cuanter",
  description: "Generated by Cuanter",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* <ConfigureAmplifyClientSide /> */}
        <PayPalProvider payPalSDKUrl={payPalSDKUrl} payPalClientId={payPalClientId}>
          {children}
        </PayPalProvider>
        <Toaster />
      </body>
    </html>
  )
}
